# Generated by Django 3.0.4 on 2020-03-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('CSS', 'CSS'), ('HTML', 'HTML'), ('JSON', 'JSON'), ('AJAX', 'AJAX'), ('JavaScript', 'JavaScript'), ('Python', 'Python'), ('Django', 'Django'), ('Java', 'Java'), ('React', 'React'), ('Ruby', 'Ruby'), ('.Net', '.Net'), ('C', 'C'), ('C#', 'C#')], default='english', max_length=100),
        ),
        migrations.AddField(
            model_name='language',
            name='slug',
            field=models.CharField(default=models.CharField(choices=[('CSS', 'CSS'), ('HTML', 'HTML'), ('JSON', 'JSON'), ('AJAX', 'AJAX'), ('JavaScript', 'JavaScript'), ('Python', 'Python'), ('Django', 'Django'), ('Java', 'Java'), ('React', 'React'), ('Ruby', 'Ruby'), ('.Net', '.Net'), ('C', 'C'), ('C#', 'C#')], default='english', max_length=100), max_length=50, unique=True),
        ),
    ]
