# Generated by Django 3.0.4 on 2020-03-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200310_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('METHOD', 'METHOD'), ('FUNCTION', 'FUNCTION'), ('OPERATOR', 'OPERATOR'), ('HELPER FUNCTION', 'HELPER FUNCTION')], default='code', max_length=100),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.CharField(default='code', max_length=100, unique=True),
        ),
    ]
