# Generated by Django 3.0.4 on 2020-03-11 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200311_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Tag'),
        ),
    ]
