# Generated by Django 3.0.4 on 2020-03-11 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200311_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.Tag'),
        ),
    ]
